### PR TITLE
force lowercase headers and force uppercase method

### PR DESCRIPTION
**Pull request by eyJhb**
Fixes issue #53 as well as forcing methods to be uppercase.
Comments are welcome!

### CODE REVIEW

**Comment by dydek** [comment]
Hi @eyJhb , I've found the same issue lately ( eg using JS `fetch` with custom headers gives you the mixed headers with title and lowercase style) - Don't you think that the method https://github.com/belyalov/tinyweb/blob/master/tinyweb/server.py#L134 should also be changed? I solved the issue differently, by using the same ( and consistent ) lower-cased headers names ( eg in the method mentioned above ) across the source code and changing the https://github.com/belyalov/tinyweb/blob/master/tinyweb/server.py#L99 to provide also lowercased headers. 

I can help write some additional tests to ensure everything is working as expected with all the needed cases, but I'm not so sure if @belyalov still maintains this project.

**Comment by richardcockerill** [comment]
I experience a variation on this  problem too regarding Content-Length and Content-Type on PUT and POST requests when using vite development server while developing a client side frontend with a tinyweb backend. The vite dev server proxy mutated the headers to lower case before forwarding to my tiny web backend and the headers failed to match and the request bodies were not read. I had to fix the string literals at https://github.com/belyalov/tinyweb/blob/master/tinyweb/server.py#L134 and https://github.com/belyalov/tinyweb/blob/master/tinyweb/server.py#L137 too

**Comment by eyJhb** [comment]
@FabianClemenz  any chance this could be merged?

**Comment by belyalov** [comment]
Thanks, it makes sense to me.

**Pull request merged**
